apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-backend
  labels:
    app: "python-guestbook-backend"
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: python-guestbook-backend
    tier: backend
  ports:
  - name: http-server
    port: 8080
    targetPort: http-server
