deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
  useTestSchema: true
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 2

chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB

monitoring:
  serviceMonitor:
    enabled: true

test:
  enabled: false

lokiCanary:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
