grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 1d
    replicas: 2
    replicaExternalLabelName: "__replica__"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

kubeEtcd:
  service:
    targetPort: 2381
