persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
      access: proxy
      isDefault: true
