deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
  useTestSchema: true

test:
  enabled: false

lokiCanary:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0