grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 1d
    replicas: 2
    replicaExternalLabelName: "__replica__"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
