apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook-frontend
spec:
  selector:
    matchLabels:
      app: python-guestbook-frontend
      tier: frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
