apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: python-guestbook-frontend
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: http-server
